services:
  speedtest-dashboard:
    build: .
    container_name: speedtest-dashboard
    ports:
      - "3667:3667"
    volumes:
      - ./data:/app/data
    environment:
      - AUTO_TEST_ENABLED=true       # Set to 'false' to disable automatic tests
      - AUTO_TEST_INTERVAL=1500       # Interval in seconds (86400 = daily)
      - AUTO_TEST_PROVIDER=both      # 'openspeedtest', 'speedsmart', or 'both'
      - DELAY_BETWEEN_TESTS=1500       # Delay in seconds between tests when running both (1 minute)
    restart: unless-stopped
